In [1]:
a=10
print(a)

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
cvalues= [20,34,45.1]
#conver values  into 1-d array
c=np.array(cvalues)
print(c)
#celsius to fahrenheit
print(c*9/5 + 32)
array1=np.array([[21,22,23,45],[34,45,78,34]],dtype=float)
#Myarray=numpy.array([1,2,3,4])
#print array
print(array1)
print(array1.shape)
print(array1.itemsize)
print(array1.ndim)
import numpy as np
threeD=np.array([[1,2,3],[4,5,6],[1,1,1],[2,2,2]],dtype=complex)
print(threeD)
print(threeD.shape)
print(threeD.itemsize)
print(threeD.ndim)

10
[1 2 3 4 5]
<class 'numpy.ndarray'>
[20.  34.  45.1]
[ 68.    93.2  113.18]
[[21. 22. 23. 45.]
 [34. 45. 78. 34.]]
(2, 4)
8
2
[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [2.+0.j 2.+0.j 2.+0.j]]
(4, 3)
16
2
